### ISSUE TITLE
Sync client does not launch under Mac OS 10.9.2

### ISSUE THREAD

**Issue by wagmatthias** [pydio/pydio-sync-java#57]
The sync client does not launch at all. 
/var/system.log shows the following error:
12.05.14 09:17:26,760 com.apple.launchd.peruser.502[159]: (io.pyd.synchro.Desktop.120064[23395]) Exited with code: 1

I am on Mac OS 10.9.2 using Java 7 now. Just recently upgraded from Java 6 in an attempt to fix the above issue. But to no avail.

We are currently evaluating Pydio as an alternative to owncloud but syncing our Macs is a MUST.

**Comment by cashxx** [comment]
I just downloaded Pydio 0.8.4 and getting an error on 10.8.5 and 10.10.2 that is similar.  It asked that I install Java 1.6 and did so, but still won't launch.  Double click the app and nothing happens.  

Is there another version I should be using?  Where is this python version?

Error:
3/5/15 3:54:17.731 PM com.apple.xpc.launchd[1]: (io.pyd.synchro.Desktop.123856[1174]) Service exited with abnormal code: 1

**Comment by cdujeu** [comment]
See https://pyd.io/apps/pydio-sync
